- targets:
    - ec2-2.internal:8081
  labels:
    service: auth-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - ec2-2.internal:8082
  labels:
    service: user-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - ec2-2.internal:8083
  labels:
    service: editor-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - ec2-2.internal:8084
  labels:
    service: authz-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - ec2-1.internal:8080
  labels:
    service: api-gateway-server
    ec2: ec2-1
    __metrics_path__: /actuator/prometheus

- targets:
    - ec2-3.internal:9121
  labels:
    service: redis-server
    ec2: ec2-3
    __metrics_path__: /metrics
