- targets:
    - auth-service:8081
  labels:
    service: auth-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - user-service:8082
  labels:
    service: user-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - editor-service:8083
  labels:
    service: editor-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - authz-service:8084
  labels:
    service: authz-service
    ec2: ec2-2
    __metrics_path__: /actuator/prometheus

- targets:
    - gateway-service:8080
  labels:
    service: gateway-service
    ec2: ec2-1
    __metrics_path__: /actuator/prometheus

- targets:
    - central-redis-exporter-dev:9121
  labels:
    service: redis-server
    ec2: ec2-3
    __metrics_path__: /metrics
